-- ⚠️ FORCE FIX: Recreate Chat Tables
-- This script drops existing chat tables to resolve schema mismatches (e.g. missing room_id)

DROP TABLE IF EXISTS "public"."messages" CASCADE;
DROP TABLE IF EXISTS "public"."chat_rooms" CASCADE;

-- Create Chat Rooms table
CREATE TABLE "public"."chat_rooms" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "name" text NOT NULL,
    "description" text,
    "is_private" boolean DEFAULT false,
    "created_by" uuid REFERENCES auth.users(id),
    "min_level" integer DEFAULT 0,
    CONSTRAINT "chat_rooms_pkey" PRIMARY KEY ("id")
);

-- Create Messages table
CREATE TABLE "public"."messages" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "room_id" uuid REFERENCES "public"."chat_rooms"("id") ON DELETE CASCADE NOT NULL,
    "user_id" uuid REFERENCES "auth"."users"("id") ON DELETE SET NULL,
    "content" text NOT NULL,
    CONSTRAINT "messages_pkey" PRIMARY KEY ("id")
);

-- Enable RLS
ALTER TABLE "public"."chat_rooms" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."messages" ENABLE ROW LEVEL SECURITY;

-- Policies for Chat Rooms
CREATE POLICY "Allow public read access to chat_rooms"
ON "public"."chat_rooms"
FOR SELECT
TO public
USING (true);

CREATE POLICY "Allow authenticated users to insert chat_rooms"
ON "public"."chat_rooms"
FOR INSERT
TO authenticated
WITH CHECK (true);

-- Policies for Messages
CREATE POLICY "Allow public read access to messages"
ON "public"."messages"
FOR SELECT
TO public
USING (true);

CREATE POLICY "Allow authenticated users to insert messages"
ON "public"."messages"
FOR INSERT
TO authenticated
WITH CHECK ((auth.uid() = user_id));

-- Add tables to realtime publication (Safely)
DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE messages;
  EXCEPTION WHEN duplicate_object THEN
    NULL;
  END;
  
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE chat_rooms;
  EXCEPTION WHEN duplicate_object THEN
    NULL;
  END;
END $$;

-- Grant permissions
GRANT SELECT ON TABLE "public"."chat_rooms" TO "anon";
GRANT SELECT ON TABLE "public"."chat_rooms" TO "authenticated";
GRANT SELECT, INSERT ON TABLE "public"."messages" TO "authenticated";
GRANT SELECT ON TABLE "public"."messages" TO "anon";

-- SEED DATA
INSERT INTO "public"."chat_rooms" ("name", "description", "is_private", "min_level")
VALUES ('Genel Piyasalar', 'Canlı yayın ve piyasalar hakkında genel sohbet.', false, 0);
