-- Create Chat Rooms table
CREATE TABLE IF NOT EXISTS "public"."chat_rooms" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "name" text NOT NULL,
    "description" text,
    "is_private" boolean DEFAULT false,
    "created_by" uuid REFERENCES auth.users(id),
    "min_level" integer DEFAULT 0,
    CONSTRAINT "chat_rooms_pkey" PRIMARY KEY ("id")
);

-- Create Messages table
CREATE TABLE IF NOT EXISTS "public"."messages" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "room_id" uuid REFERENCES "public"."chat_rooms"("id") ON DELETE CASCADE NOT NULL,
    "user_id" uuid REFERENCES "auth"."users"("id") ON DELETE SET NULL,
    "content" text NOT NULL,
    CONSTRAINT "messages_pkey" PRIMARY KEY ("id")
);

-- Enable RLS
ALTER TABLE "public"."chat_rooms" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."messages" ENABLE ROW LEVEL SECURITY;

-- Policies (Drop first to avoid errors on re-run)
DROP POLICY IF EXISTS "Allow public read access to chat_rooms" ON "public"."chat_rooms";
CREATE POLICY "Allow public read access to chat_rooms"
ON "public"."chat_rooms"
FOR SELECT
TO public
USING (true);

DROP POLICY IF EXISTS "Allow authenticated users to insert chat_rooms" ON "public"."chat_rooms";
CREATE POLICY "Allow authenticated users to insert chat_rooms"
ON "public"."chat_rooms"
FOR INSERT
TO authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read access to messages" ON "public"."messages";
CREATE POLICY "Allow public read access to messages"
ON "public"."messages"
FOR SELECT
TO public
USING (true);

DROP POLICY IF EXISTS "Allow authenticated users to insert messages" ON "public"."messages";
CREATE POLICY "Allow authenticated users to insert messages"
ON "public"."messages"
FOR INSERT
TO authenticated
WITH CHECK ((auth.uid() = user_id));

-- Add tables to realtime publication (Safely)
DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE messages;
  EXCEPTION WHEN duplicate_object THEN
    NULL; -- already exists
  END;
  
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE chat_rooms;
  EXCEPTION WHEN duplicate_object THEN
    NULL; -- already exists
  END;
END $$;

-- Grant permissions
GRANT SELECT ON TABLE "public"."chat_rooms" TO "anon";
GRANT SELECT ON TABLE "public"."chat_rooms" TO "authenticated";
GRANT SELECT, INSERT ON TABLE "public"."messages" TO "authenticated";
GRANT SELECT ON TABLE "public"."messages" TO "anon";

-- SEED DATA: Ensure 'Genel Piyasalar' room exists
INSERT INTO "public"."chat_rooms" ("name", "description", "is_private", "min_level")
SELECT 'Genel Piyasalar', 'Canlı yayın ve piyasalar hakkında genel sohbet.', false, 0
WHERE NOT EXISTS (
    SELECT 1 FROM "public"."chat_rooms" WHERE "name" = 'Genel Piyasalar'
);
